import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import { ModeToggle } from "@/components/darkmode-toggle";
import { NavBar } from "@/components/navbar";
import PrelineScript from "@/components/PrelineScript";
import Header from "@/components/header";
import Sidebar from "@/components/side-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
       <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange> 
        <Header />
        <Sidebar />
        {children}
        </ThemeProvider>
        </body>
        <PrelineScript />
    </html>
  );
}
